server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Inventory service routes
        - id: inventory-service-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventories/**

        # Order service routes
        - id: orders-service-route
          uri: lb://orders-service
          predicates:
            - Path=/api/v1/orders/**

        # Product service routes
        - id: products-service-route
          uri: lb://products-service
          predicates:
            - Path=/api/v1/products/**

        # Discovery Server routes
        - id: discovery-service-route
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        # Discovery Server Static routes
        - id: discovery-service-static-route
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

      default-filters:
        - SaveSession
        - TokenRelay

  # Keycloak
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            scope: openid
            client-id: microservices_client
            client-secret: HAVz0radwfOEsapxT5e8GdvckcOlFgD6
            authorization-grant-type: authorization_code
            redirect-uri: { baseUrl }/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/microservices-realm

# Eureka client
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/

# Log
logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info