server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db_orders_service
    username: magadiflo
    password: magadiflo

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
