server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db_inventory_service
    username: magadiflo
    password: magadiflo

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug