server:
  port: 0

spring:
  application:
    name: notifications-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notifications-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Eureka client
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator/notifications

